	
<field:onlynet itemname="联系方式限制" autofield="1" type="int" isnull="true" default="1"  maxlength="250" issearch="" isshow="" state="1">	
</field:onlynet>	
	
<field:sex itemname="性别" autofield="1" type="radio" isnull="true" default="男,女,保密"  maxlength="250" issearch="" isshow="" state="1">	
</field:sex>	
	
<field:uname itemname="昵称/公司名称" autofield="1" type="textchar" isnull="true" default=""  maxlength="30" issearch="" isshow="" state="1">	
</field:uname>	
	
<field:qq itemname="QQ" autofield="1" type="textchar" isnull="true" default=""  maxlength="12" issearch="" isshow="" state="1">	
</field:qq>	
	
<field:msn itemname="MSN" autofield="1" type="textchar" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="1">	
</field:msn>	
	
<field:tel itemname="电话号码" autofield="1" type="text" isnull="true" default=""  maxlength="15" issearch="" isshow="" state="1">	
</field:tel>	
	
<field:mobile itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="15" issearch="" isshow="" state="1">	
</field:mobile>	
	
<field:place itemname="目前所在地" autofield="1" type="int" default="0"  maxlength="5" issearch="0" isshow="0" state="1">	
</field:place>	
	
	
<field:oldplace itemname="家乡所在地" autofield="1" type="int" default="0"  maxlength="5" issearch="0" isshow="0" state="1">	
</field:oldplace>	
	
	
<field:birthday itemname="生日" autofield="1" type="datetime" isnull="true" default=""  maxlength="250" issearch="" isshow="" state="1">	
</field:birthday>	
	
<field:star itemname="星座" autofield="1" type="int" isnull="true" default="1"  maxlength="6" issearch="" isshow="" state="1">	
</field:star>	
	
<field:income itemname="收入" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:income>	
	
<field:education itemname="学历" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:education>	
	
<field:height itemname="身高" autofield="1" type="int" isnull="true" default="160"  maxlength="5" issearch="" isshow="" state="1">	
</field:height>	
	
<field:bodytype itemname="体重" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:bodytype>	
	
<field:blood itemname="血型" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:blood>	
	
<field:vocation itemname="职业" autofield="1" type="text" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:vocation>	
	
<field:smoke itemname="吸烟" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:smoke>	
	
<field:marital itemname="婚姻状况" autofield="1" type="text" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:marital>	
	
<field:house itemname="住房" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:house>	
	
<field:drink itemname="饮酒" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:drink>	
	
<field:datingtype itemname="交友" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:datingtype>	
	
<field:language itemname="语言" autofield="1" type="checkbox" isnull="true" default="普通话,上海话,广东话,英语,日语,韩语,法语,意大利语,德语,西班牙语,俄语,阿拉伯语"  maxlength="250" issearch="" isshow="" state="1">	
</field:language>	
	
	
<field:nature itemname="性格" autofield="1" type="checkbox" isnull="true" default="性格外向,性格内向,活泼开朗,豪放不羁,患得患失,冲动,幽默,稳重,轻浮,沉默寡言,多愁善感,时喜时悲,附庸风雅,能说会道,坚强,脆弱,幼稚,成熟,快言快语,损人利己,狡猾善变,交际广泛,优柔寡断,自私,真诚,独立,依赖,难以琢磨,悲观消极,郁郁寡欢,胆小怕事,乐观向上,任性,自负,自卑,拜金,温柔体贴,小心翼翼,暴力倾向,逆来顺受,不拘小节,暴躁,倔强,豪爽,害羞,婆婆妈妈,敢做敢当,助人为乐,耿直,虚伪,孤僻,老实,守旧,敏感,迟钝,婆婆妈妈,武断,果断,刻薄"  maxlength="250" issearch="" isshow="" state="1">	
</field:nature>	
	
<field:lovemsg itemname="人生格言" autofield="1" type="text" isnull="true" default=""  maxlength="100" issearch="" isshow="" state="1">	
</field:lovemsg>	
	
<field:address itemname="家庭住址" autofield="1" type="text" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="1">	
</field:address>	
	
<field:uptime itemname="更新时间" autofield="1" type="int" isnull="true" default=""  maxlength="10" issearch="" isshow="" state="1">	
</field:uptime>	
